version: "3"
services:
  frontend-green:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: frontend-green
    ports:
      - "${GREEN_FRONTEND_PORT}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge